clone:
  depth: full
pipelines:
 pipelines:
  default:
    - step:
        name: Sync GitHub Mirror
        image: alpine/git:latest
        clone:
          enabled: false
        script:
          - git clone --bare git@bitbucket.org:luisgarciar/helmholtz.git
          - cd RepoName.git
          - git push --mirror git@github.com:luisgarciar/ml_helmholtz_solvers.git
